name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx for PHP
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/phpcrudalpine_php:latest
      - name: Set up Docker Buildx for Apache
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/apache/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/phpcrudalpine_apache:latest
      - name: Set up Docker Buildx for MySQL
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/phpcrudalpine_mysql:latest
