name: TranslateThis
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #            - name: Install Composer Dependencies
      #              working-directory: ./app
      #              run: composer install --prefer-dist
      #            - name: Run Tests
      #              working-directory: ./app
      #              run: composer run-phpunit
      - run: docker build --target app -t raynorcorgio/php-composer:1.0 -f ./docker/php/Dockerfile .
      - run: docker build -t raynorcorgio/apache-php:1.0 -f ./docker/apache/Dockerfile .
      - run: docker build -t raynorcorgio/mysql-php:1.0 -f ./docker/mysql/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push raynorcorgio/php-composer:1.0
      - run: docker push raynorcorgio/apache-php:1.0
      - run: docker push raynorcorgio/mysql-php:1.0
